services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: development
    volumes:
      - ./api/src:/app/api/src
      - ./shared:/app/shared
    ports:
      - '3001:3000'

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      target: development
    volumes:
      - ./web/src:/app/web/src
      - ./web/public:/app/web/public
      - ./shared:/app/shared
    ports:
      - '3000:3000'
    depends_on:
      - api